### ISSUE TITLE
Ajustes de README.md

### ISSUE THREAD

**Issue by Rian-Sm** [seyadeodin/fullstack#1]
Ajusta o readme pra eu entender o que vc vai fazer no projeto, pufavo

**Comment by seyadeodin** [comment]
Acho que esse  repo provavelmente nao vai receber mais nada, criei ele apenas para testar o proxy reverso do NGINX e   criar um esquema de CI/CD usando cronjobs e bash no VPS.  Se quiser eu posso colocar as notas do curso aqui após eu finalizar.

**Comment by Rian-Sm** [comment]
Entendi, mas é importante quem olhar o repositório entender o que está acontecendo, eu só entendi que era um repositório de estudo com sua resposta aqui, adiciona esse texto sobre o "estudo do NGINX | CI/DC e bash" no readme que vai ficar perfeito
